### PR TITLE
Add configuration options

### PR DESCRIPTION
**Pull request by mkunkel**
Create a configuration class that will allow for setting configuration options via an initializer.

Options added in this commit are for the number of backtrace lines to show, as well as how many newlines to have before and after each output.

### CODE REVIEW

**Comment by olegantonyan** [comment]
Thanks for your contribution! I really appreciate it
I think it would be nice to do 2 more things:
1. Move `print_caller_lines`, `blank_lines_top`, `blank_lines_bottom` and `config` methods into `SuperAwesomePrint` module. Because they will pollute global namespace. `sap` method sits there since it has to be global.
2. Use sensible default config if it wasn't provided in initializer. Otherwise it blows up with `undefined method 'times' for nil:NilClass`

**Comment by mkunkel** [comment]
Great points! I'll work on those, as well as getting this rebased.

**Comment by mkunkel** [comment]
I am unable to reproduce the issue of not having a default config. The configuration class should set defaults, in the case that no configuration is provided.

**Comment by olegantonyan** [comment]
Hm, it's probably my fault somewhere I don't know exactly where

**Pull request merged**
